### PR TITLE
Various fixes while testing

### PR DESCRIPTION
**Pull request by vvaldez**
Various commits based on testing.

### CODE REVIEW

**Comment by vvaldez** [comment]
Various fixes based on experiments.

**Comment by abrezhnev** [comment]
Hi Vinny,

We need to figure out how to better use github workflow to pull changes
between our repositories.
I've found this description:
https://help.github.com/articles/using-pull-requests

I tried to apply your pull request but I have few concerns. First, I
believe that the set of commits incorporated into the master repository
should maintain some general logic in the changes. It will be easier to
figure out why we made one change or another. Some of your commits make
perfect sense for your private configuration but they are not essential or
desirable for the public master branch. For example, this is applicable to
the hostname changes in the inventory file or some changes to the
configuration variables.

Another issue is with your clenup steps and corresponding tags. I like the
idea to have cleanup scripts but they should be outside of the main
playbooks. It is not enough to assign cleanup tags to some steps. This
approach will work only if you always execute playbook with the explicit
set of tags. Otherwise, if you run the playbook and do not specify tags,
all steps will be executed. We don't want to have our setup cleaned up in
this case.

It would be easier to work with the the pull request if it would have been
shorter and more focused.
It can be achieved if you checkout the master branch and diff its roles
against the final version of your development branch where you implemented
some new functionality. Then you can use the diff as a patch that
implements all desired functionality in one change. If you apply this patch
and get a new commit in the repo, you can send it as a pull request that
will be very easy to understand, discuss and apply.

What do you think? Does it make sense?

**Comment by vvaldez** [comment]
Hi Aleksandr I agree that wasn't the best pull request. Do you have time to meet in an hour to discuss? That will be 2pm EDT. I'll setup an invite if that works.

Vinny Valdez, RHCA, RHCSS, RHCVA (110-119-187)
Principal Enterprise Architect
Cloud Practice

**Comment by vvaldez** [comment]
ok

----- Original Message -----

**Comment by abrezhnev** [comment]
This is very short and clear description how to use branches and produce
patches that can be easily consumed with git:

https://ariejan.net/2009/10/26/how-to-create-and-apply-a-patch-with-git/

**Pull request closed without merging**
